name: Manual Electron Multi-Platform Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 1.0.2-alpha.0)'
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Bump version (only if different)
        run: |
          VERSION="${{ github.event.inputs.version }}"
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          if [ "$CURRENT_VERSION" != "$VERSION" ]; then
            npm version "$VERSION" --no-git-tag-version
          else
            echo "Version already set to $VERSION"
          fi

      - name: Build React app
        run: npm run build

      - name: Build and publish Electron app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm run electron:build
