name: Manual Electron Multi-Platform Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (es. 1.0.2)'
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set version in package.json
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Build React app
        run: npm run build

      - name: Build Electron app and publish to GitHub Releases
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run electron:build
